### ISSUE TITLE
State diagrams do not work

### ISSUE THREAD

**Issue by hgc2002** [dkd/plantuml#12]
Hello,

I've installed the PlantUML plugin for Redmine and everything looks fine.

But I cannot make any State diagram to work. Examples:

```
[*] --> State1
State1 --> [*]
State1 : this is a string
State1 : this is another string

State1 -> State2
State2 --> [*]
```

(yes, I used the start and end tags)

The jar versions I've tested are:

```
plantuml-8059.jar

plantuml.1.2017.16.jar
```

This is the way I use it:
`
/usr/bin/java -Djava.io.tmpdir=/var/tmp -Djava.awt.headless=true -jar /var/www/redmine/plugins/plantuml/bin/20171003-plantuml.1.2017.16.jar ${@}`

As I said before, every other diagram works fine, but not State diagrams.

Thanks for your help

**Comment by hgc2002** [comment]
Ok, this means there is an issue with GraphViz installation.
See http://plantuml.com/graphviz-dot

Then try the following diagram:
@startuml
testdot
@enduml

**Comment by mrResident** [comment]
Hello! I have a similar problem.
Performed the recommended actions, created a script and registered the path in the plugin's settings. If I run the script manually, then everything is fine, but if I do the same in redmine, I get the "graphviz problems" error message. Maybe this is due to access rights? On behalf of what user should the script run? For example, I'm using bitnami redmine stack.
Example error message in redmine (see attach)
![plantuml_9a2dd95042d65f50460ded4c1efb4a4d4e56d5adfaf8d159d5ccaa877b108f7e](https://user-images.githubusercontent.com/3408881/32052094-cb931bc8-ba5f-11e7-85a8-47294d84e23e.png)

**Comment by ncreuschling** [comment]
We do not provide support for your individual installations or use cases.
